resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

pr: none
trigger:
  - master

variables:
  - group: InfoSec-SecurityResults
  - name: tags
    value: production,externalfacing
  - name: serviceTreeID
    value: c3a0680e-4563-4c47-bce9-710df6e5485c
  - name: adoNpmFeedBaseUrl
    value: https://pkgs.dev.azure.com/domoreexp/_apis/packaging/feeds/npm-mirror

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates

  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
    stages:
      - stage: release
        variables:
          # OPTIONAL: Set this varibale to 'true' to enable signing in a target stage.
          # Remove if signing is not required.
          Build.ESRP.CodeSign.Enabled: true
          # OPTIONAL: To disable required tools not applicable in the pipeline set to false.
          # Supported values: BinSkim, Roslyn, ESLint, PREFast.
          Build.SDL.<Roslyn>.Enabled: false
          Build.SDL.<ESLint>.Enabled: true
        jobs:
          - job: Release
            variables:
              - group: oss-secrets
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              image: ubuntu-latest
              os: linux
            steps:
              - checkout: self
                persistCredentials: true # fix for beachball: https://github.com/microsoft/beachball/issues/674
              - script: yarn
                displayName: yarn
              - script: |
                  yarn ci
                displayName: build and test [test]
              - script: |
                  git config user.email "teams-globalization@microsoft.com"
                  git config user.name "Globalization Team Account"
                displayName: Configure git for release
              - script: |
                  echo "always-auth=true" > .npmrc
              - task: npmAuthenticate@0
                inputs:
                  workingFile: ".npmrc"
              - script: yarn release -y
                displayName: Release to the npm registry
              - task: 1ES.PublishPipelineArtifact@1
                displayName: 📒 Publish Manifest
                inputs:
                  artifactName: SBom-$(System.JobAttempt)
                  targetPath: $(System.DefaultWorkingDirectory)/_manifest
              - template: .azure-devops/steps/pierce-ado-npm-mirror-cache.yml@self
                parameters:
                  adoNpmFeedPat: $(adoNpmFeedPat)
                  adoNpmFeedBaseUrl: $(adoNpmFeedBaseUrl)